### ISSUE TITLE
.NET core version

### ISSUE THREAD

**Issue by HariSeldon23** [AuDigitalHealth/hi-b2b-client-dotnet#1]
I am looking at using this as a base for developing a .NET core version.

Would this be of interest?

**Comment by philipwilford** [comment]
Hi justin

Yes. Would be interested in core. 
Not sure soap is supported in core though?

Cheers
Philip

**Comment by HariSeldon23** [comment]
Been doing some research. We initially wanted to do a .NET core version (3) that exposes the functions via GRPC https://grpc.io/ but due to the lack of SOAP in .NET core it's thrown us off.

There is a SOAP extension for .NET Core https://github.com/DigDes/SoapCore however we may just finish our current dev in .NET and then once .NET 5 and .NET Core 3 stabilizes port it then.

**Comment by philipwilford** [comment]
Thanks Justin,

We did look at porting code to Core but due to the lack of support for
SOAP, decided to leave as is until MS provide it.

**Comment by HariSeldon23** [comment]
Makes complete sense. I'll close this issue. 

Thanks again for the help :)
