### ISSUE TITLE
How to get Certificate and Use in .NET Core

### ISSUE THREAD

**Issue by npdesai** [AuDigitalHealth/hi-b2b-client-dotnet#2]
I want to get certificate .NET Core code.

I am using below code for getting certificate, please review and guide me how i get the certificate.

![image](https://user-images.githubusercontent.com/17276920/57672145-7b44e380-7634-11e9-843e-2f10dd43e564.png)

What i use as Serial Number?

**Comment by npdesai** [comment]
What i have to use as Serial Number ?

**Comment by philipwilford** [comment]
You should have a NASH Certificate - in there is the serial number.
you can use a thumbprint instead, but then change the X509Findtype to that

**Comment by npdesai** [comment]
![image](https://user-images.githubusercontent.com/17276920/57673408-6fa7eb80-7639-11e9-8e1d-258e8e0e000b.png)

Hi,
I have used thumbprint as per your suggestion but still getting same exception as "Certificate was not found with criteria"

**Comment by npdesai** [comment]
Thumbprint I get from certificate:

![image](https://user-images.githubusercontent.com/17276920/57673498-d62d0980-7639-11e9-87e5-27438a70e212.png)

![image](https://user-images.githubusercontent.com/17276920/57673477-c6adc080-7639-11e9-934e-1bac1e91ed75.png)

**Comment by philipwilford** [comment]
You also need to import the Root and OCA Certificates in your Trusted Store
so that your computer can trust the cert you are using.

These should have come with the p12 file (might be crt files)

[image: image.png]

**Comment by npdesai** [comment]
![image](https://user-images.githubusercontent.com/17276920/57682212-ebf8f980-764e-11e9-9619-8bdaff054b77.png)

Got the certificate using this code
